AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to deploy a React app with S3 and CloudFront using OAC"

Resources:
  WorkshopUIBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "workshop-ui-dev"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WorkshopUIBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${WorkshopUIBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ReactAppCDN}"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "ReactAppOAC"
        Description: "OAC for React S3 Hosting"
        SigningProtocol: "sigv4"
        SigningBehavior: "always"
        OriginAccessControlOriginType: "s3"

  ReactAppCDN:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: "index.html"
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WorkshopUIBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: "PriceClass_100"
        HttpVersion: "http2"
        DefaultRootObject: "index.html"

Outputs:
  S3BucketName:
    Description: "S3 bucket name for the React app"
    Value: !Ref WorkshopUIBucket

  CloudFrontURL:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${ReactAppCDN.DomainName}"

  CloudFrontDistributionID:
    Description: "CloudFront Distribution ID"
    Value: !Ref ReactAppCDN
