AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to deploy a React app with S3 and CloudFront using OAC"

Resources:
  WorkshopUIBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "workshop-ui-dev"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
    DeletionPolicy: Retain

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WorkshopUIBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${WorkshopUIBucket}/*

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "ReactAppOAC"
        Description: "OAC for React S3 Hosting"
        SigningProtocol: "sigv4"
        SigningBehavior: "always"
        OriginAccessControlOriginType: "s3"

  ReactAppCDN:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: "index.html"
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
            DomainName: !Join ["", [!Ref "WorkshopUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com"]]
            Id: !Join ["", ["Custom-", !Ref "WorkshopUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com/"]]
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies: {Forward: "none"}
            Headers: ["Origin"]
          TargetOriginId: !Join ["", ["Custom-", !Ref "WorkshopUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com/"]]
          ViewerProtocolPolicy: "redirect-to-https"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: "PriceClass_200"
        HttpVersion: "http2"
        DefaultRootObject: "index.html"

Outputs:
  S3BucketName:
    Description: "S3 bucket name for the React app"
    Value: !Ref WorkshopUIBucket

  CloudFrontURL:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${ReactAppCDN.DomainName}"

  CloudFrontDistributionID:
    Description: "CloudFront Distribution ID"
    Value: !Ref ReactAppCDN
